name: Terraform
on: 
  workflow_dispatch:
    inputs:
      instance_name:
        description: 'Enter instance name'
        required: true

jobs:
  teraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: us-east-1

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 1.0.1
          terraform_wrapper: false
          
    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -var 'instance_name= ${{ inputs.instance_name }}'

    - name: Terraform Apply -var
      run: terraform apply -auto-approve -var 'instance_name= ${{ inputs.instance_name }}'
      
    - name: Wait
      run: sleep 120
      
    - name: Destroy
      run: terraform destroy -auto-approve
